### ISSUE TITLE
Support linux-docker-android (and other) stack

### ISSUE THREAD

**Issue by azat** [bitrise-steplib/steps-project-scanner#67]
(Maybe I missing something, if so, please refer me to the appropriate documentation or just give an example)

So suppose you have regular C project, that you want to check for cross compilation on android and configure it via `bitrise.yml`, i.e.

```yml
---
format_version: 5
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  steps:
  - git-clone: {}
  - script:
      deps:
        apt_get:
        - name: ninja-build
      inputs:
      - content: |-
          set -e
          set -x

          mkdir libevent
          cd libevent
          cmake -d
            -DCMAKE_TOOLCHAIN_FILE=/opt/android-ndk/build/cmake/android.toolchain.cmake
            -DANDROID_TOOLCHAIN=gcc
            -G Ninja
            /bitrise/src
          ninja
  meta:
    bitrise.io:
      stack: linux-docker-android
```

But, since scanner cannot detect it you need to configure it via workflow editor manually. Am I right?

So it would be great if bitrise will parse this yml correctly without using workflow editor in web
